### ISSUE TITLE
Feature Request: Add netcat package to base

### ISSUE THREAD

**Issue by S3ntinelX** [KatharaFramework/Docker-Images#1]
I was just wondering if it would be possible to add netcat to the base image as it is a useful and lightweight networking tool.

Thanks a lot
Sentinel

**Comment by lorenzo93** [comment]
Hi @S3ntinelX,

it is of course possible to add netcat to the base image. I don't know why it wasn't already there.
Just changed the Dockerfile and I'm building the new images right now. In a couple of minutes they'll be ready and pushed to the dockerhub.

**Comment by S3ntinelX** [comment]
Thanks a lot
