### ISSUE TITLE
Buster / Bullseye version

### ISSUE THREAD

**Issue by arodier-pirum** [KatharaFramework/Docker-Images#2]
How difficult would it be to have a buster or bullseye version for the docker images ?

**Comment by lorenzo93** [comment]
Hi @arodier-pirum ,

I can prepare those images between today and tomorrow. We were already thinking about creating newer versions of the images :)

I'll let you know as soon as they are published

**Comment by arodier-pirum** [comment]
Thank you, Lorenzo.
And congratulations for your great work, this is very useful.

**Comment by lorenzo93** [comment]
Hi @arodier-pirum ,

I've created the new Dockerfiles and I'm now pushing the images to the Dockerhub.
The images are tagged with the `debian10` tag.

To use them in Kathará, you can both change the default image using `kathara settings` or specify it in your `lab.conf` file. In both case, you need to refer to this images like this "kathara/quagga:debian10"

**Comment by arodier-pirum** [comment]
Thanks, that was very quick!
