### ISSUE TITLE
[Feature request] Upgrade the python version on images

### ISSUE THREAD

**Issue by Aperence** [KatharaFramework/Docker-Images#8]
Hi,

It would be interesting according to me to be able to select a newer version of python on some images, per example python 3.8 or higher, to be able to make tests with some protocol implementations (aioquic for example which requires at least python 3.8).

Thanks in advance

**Comment by Aperence** [comment]
Update : I created a docker image `aperence/kathara-quic` which has python3.10 installed by default, so feel free to use it if you need to use a newer version of python

**Comment by tcaiazzi** [comment]
Hi @Aperence,

We will update all the images soon, but we need to carefully test all the official labs before. 
In the meanwhile, you can find the new images in the [develop branch](https://github.com/KatharaFramework/Docker-Images/tree/develop). 

The new images are based on Debian12 and have Python3.11 installed. 
Moreover, you can find many new images to test several technologies. 

The complete list includes:
- `kathara/base`: used to build all other images. It contains a variety of network tools and some complex services like bind, apache, etc.
- `kathara/quagga`: extends the base image adding [Quagga](https://www.nongnu.org/quagga/).
- `kathara/frr`: extends the base image adding [FRRouting](https://frrouting.org/).
- `kathara/openbgpd`: extend the base image adding the [OpenBGPD daemon](https://www.openbgpd.org/).
- `kathara/krill`: extends the base image adding [Krill RPKI Certificate Authority](https://www.nlnetlabs.nl/projects/rpki/krill/).
- `kathara/routinator`: extends the base image adding [Routinator RPKI Relying Party](https://www.nlnetlabs.nl/projects/rpki/routinator/).
- `kathara/rpki-client`: extends the base image adding [OpenBGPD RPKI Client](https://www.rpki-client.org).
- `kathara/bird`: extends the base image adding [BIRD](https://bird.network.cz/).
- `kathara/rift-python`: extends the base image adding [Routing In Fat Trees (RIFT) Python Implementation](https://github.com/brunorijsman/rift-python).
- `kathara/sdn`: extends the base image adding [OpenVSwitch](https://www.openvswitch.org/) and [Ryu SDN controller](https://osrg.github.io/ryu/).
- `kathara/p4`: extends the base image adding [Behavioral Model (bmv2)](https://github.com/p4lang/behavioral-model) to compile and run P4-compliant programmable switches.
